'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace lab_44_mvc_framework

    Partial Public Class User
        Public Property UserID As Integer
        Public Property CategoryID As Nullable(Of Integer)
        Public Property UserName As String
        Public Property DateOfBirth As Nullable(Of Date)
        Public Property isValid As Nullable(Of Boolean)
        Public Property CompanyID As Nullable(Of Integer)
    
        Public Overridable Property Category As Category
        Public Overridable Property Company As Company
    
    End Class

End Namespace
